<!DOCTYPE html>
<html lang="ar" dir="rtl">
<head>
<meta charset="UTF-8" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<title>ุญุณุงุจ ุงููุตุงุฑูู ุงูุดูุฑูุฉ ุงููุชูุฏู</title>
<style>
  body {
    font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
    max-width: 700px;
    margin: 20px auto;
    background: linear-gradient(135deg, #667eea, #764ba2);
    color: #fff;
    padding: 20px;
    border-radius: 12px;
    box-shadow: 0 10px 25px rgba(0,0,0,0.2);
  }

  h2, h3 {
    text-align: center;
    text-shadow: 1px 1px 4px rgba(0,0,0,0.3);
  }

  label, button {
    display: block;
    margin-top: 10px;
  }

  select, input[type="text"], input[type="number"], input[type="date"] {
    padding: 8px;
    width: 100%;
    box-sizing: border-box;
    border-radius: 6px;
    border: none;
    font-size: 14px;
  }

  button.btn {
    cursor: pointer;
    background-color: #9f7aea;
    color: white;
    font-weight: bold;
    border: none;
    padding: 10px;
    border-radius: 8px;
    transition: background-color 0.3s ease;
  }

  button.btn:hover {
    background-color: #7c3aed;
  }

  table {
    width: 100%;
    border-collapse: collapse;
    margin-top: 20px;
    background-color: rgba(255, 255, 255, 0.15);
    border-radius: 10px;
    overflow: hidden;
  }

  th, td {
    border: none;
    padding: 10px;
    text-align: center;
    color: #fff;
  }

  th {
    background-color: rgba(0,0,0,0.25);
  }

  button.action-btn {
    background: none;
    border: none;
    color: #fff;
    font-size: 18px;
    margin: 0 5px;
  }

  button.action-btn:hover {
    color: #d1c4e9;
  }

  #filters {
    margin-top: 20px;
    display: flex;
    gap: 10px;
    flex-wrap: wrap;
  }

  #filters > * {
    flex: 1;
    min-width: 120px;
  }

  #chart-container {
    margin-top: 30px;
    background-color: rgba(255, 255, 255, 0.15);
    padding: 15px;
    border-radius: 10px;
  }

  #export-btn {
    margin-top: 15px;
  }

  #input-ุชุตููู-ุฌุฏูุฏ, #btn-ุฅุถุงูุฉ-ุชุตููู {
    margin-top: 5px;
    display: none;
  }
</style>
</head>
<body>

<h2>ุญุณุงุจ ุงููุตุงุฑูู ุงูุดูุฑูุฉ ุงููุชูุฏู</h2>

<form id="form-ูุตุฑููุงุช">
  <label>ุงูููุน:
    <select id="input-ููุน" required>
      <option value="ูุตุฑูู">ูุตุฑูู</option>
      <option value="ุฏุฎู">ุฏุฎู</option>
    </select>
  </label>

  <label>ุงูุชุตููู:
    <select id="input-ุชุตููู" required></select>
    <input type="text" id="input-ุชุตููู-ุฌุฏูุฏ" placeholder="ุฃุถู ุชุตููู ุฌุฏูุฏ..." />
    <button type="button" id="btn-ุฅุถุงูุฉ-ุชุตููู">โ ุฅุถุงูุฉ ุชุตููู</button>
  </label>

  <label>ุงููููุฉ:
    <input id="input-ูููุฉ" type="number" step="0.01" min="0" required />
  </label>

  <label>ุงูุชุงุฑูุฎ:
    <input id="input-ุชุงุฑูุฎ" type="date" required />
  </label>

  <button type="submit" class="btn">โ ุฅุถุงูุฉ</button>
</form>

<div id="filters">
  <select id="ููุชุฑ-ููุน">
    <option value="ุงููู">ุงููู</option>
    <option value="ูุตุฑูู">ูุตุฑูู</option>
    <option value="ุฏุฎู">ุฏุฎู</option>
  </select>

  <select id="ููุชุฑ-ุชุตููู">
    <option value="ุงููู">ุงููู</option>
  </select>

  <input type="date" id="ููุชุฑ-ุชุงุฑูุฎ-ูู" placeholder="ูู" />
  <input type="date" id="ููุชุฑ-ุชุงุฑูุฎ-ุฅูู" placeholder="ุฅูู" />
</div>

<button id="export-btn" class="btn">โฌ๏ธ ุชุตุฏูุฑ CSV</button>

<h3>ูุงุฆูุฉ ุงููุตุงุฑูู</h3>
<table id="ุฌุฏูู-ูุตุฑููุงุช">
  <thead>
    <tr>
      <th>ุงูููุน</th>
      <th>ุงูุชุตููู</th>
      <th>ุงููููุฉ</th>
      <th>ุงูุชุงุฑูุฎ</th>
      <th>ุงูุฅุฌุฑุงุกุงุช</th>
    </tr>
  </thead>
  <tbody></tbody>
</table>

<h3>ุงูุฅุญุตุงุฆูุงุช</h3>
<div>
  <p id="ุฅุฌูุงูู-ุงูุฏุฎู">๐ฐ ุงูุฏุฎู: 0</p>
  <p id="ุฅุฌูุงูู-ุงููุตุงุฑูู">๐งพ ุงููุตุงุฑูู: 0</p>
  <p id="ุงูุตุงูู">๐ ุงูุตุงูู: 0</p>
</div>

<div id="chart-container">
  <canvas id="chart"></canvas>
</div>

<!-- ููุชุจุฉ Chart.js -->
<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>

<script>
  const STORAGE_KEY = "ูุตุฑููุงุช_ุดูุฑูุฉ_ูุชูุฏู";
  let ุจูุงูุงุช = [];
  let ุชุตูููุงุช = ["ุทุนุงู", "ููุงุตูุงุช", "ุฅูุฌุงุฑ", "ุฑุงุชุจ", "ุชุฑููู", "ุฃุฎุฑู"];
  let ุชุนุฏููIndex = null; // ููุชุงุจุนุฉ ุงูุชุนุฏูู
  let chart = null;

  // ุชุญููู ุงูุจูุงูุงุช ูู localStorage
  function ุฌูุจ_ุงูุจูุงูุงุช() {
    const data = localStorage.getItem(STORAGE_KEY);
    return data ? JSON.parse(data) : [];
  }

  // ุญูุธ ุงูุจูุงูุงุช ูู localStorage
  function ุญูุธ_ุงูุจูุงูุงุช() {
    localStorage.setItem(STORAGE_KEY, JSON.stringify(ุจูุงูุงุช));
  }

  // ุชุญุฏูุซ ููุงุฆู ุงูุชุตููู (ุงููููุฐุฌ ูุงูููุชุฑ)
  function ุชุญุฏูุซ_ุงูุชุตูููุงุช() {
    const select = document.getElementById("input-ุชุตููู");
    const filterSelect = document.getElementById("ููุชุฑ-ุชุตููู");

    // ูุณุญ ุงูุฎูุงุฑุงุช ุงูุญุงููุฉ
    select.innerHTML = "";
    filterSelect.innerHTML = '<option value="ุงููู">ุงููู</option>';

    // ุฅุถุงูุฉ ุงูุชุตูููุงุช
    ุชุตูููุงุช.forEach(cat => {
      const option1 = document.createElement("option");
      option1.value = cat;
      option1.textContent = cat;
      select.appendChild(option1);

      const option2 = document.createElement("option");
      option2.value = cat;
      option2.textContent = cat;
      filterSelect.appendChild(option2);
    });

    // ุฎูุงุฑ "ุฃุฎุฑู"
    const optionOther = document.createElement("option");
    optionOther.value = "ุฃุฎุฑู";
    optionOther.textContent = "ุฃุฎุฑู";
    select.appendChild(optionOther);
  }

  // ุฅุธูุงุฑ ุฃู ุฅุฎูุงุก ุญูู ุฅุถุงูุฉ ุชุตููู ุฌุฏูุฏ
  document.getElementById("input-ุชุตููู").addEventListener("change", () => {
    const val = document.getElementById("input-ุชุตููู").value;
    const inputNewCat = document.getElementById("input-ุชุตููู-ุฌุฏูุฏ");
    const btnAddCat = document.getElementById("btn-ุฅุถุงูุฉ-ุชุตููู");

    if(val === "ุฃุฎุฑู") {
      inputNewCat.style.display = "block";
      btnAddCat.style.display = "block";
    } else {
      inputNewCat.style.display = "none";
      btnAddCat.style.display = "none";
      inputNewCat.value = "";
    }
  });

  // ุฅุถุงูุฉ ุชุตููู ุฌุฏูุฏ
  document.getElementById("btn-ุฅุถุงูุฉ-ุชุตููู").addEventListener("click", () => {
    const inputNewCat = document.getElementById("input-ุชุตููู-ุฌุฏูุฏ");
    const newCat = inputNewCat.value.trim();
    if(newCat && !ุชุตูููุงุช.includes(newCat)) {
      ุชุตูููุงุช.push(newCat);
      ุชุญุฏูุซ_ุงูุชุตูููุงุช();
      document.getElementById("input-ุชุตููู").value = newCat;
      inputNewCat.value = "";
      inputNewCat.style.display = "none";
      document.getElementById("btn-ุฅุถุงูุฉ-ุชุตููู").style.display = "none";
      ุชุญุฏูุซ_ููุชุฑ_ุงูููู();
    } else {
      alert("ูุฑุฌู ุฅุฏุฎุงู ุชุตููู ุฌุฏูุฏ ุบูุฑ ููุฑุฑ.");
    }
  });

  // ุชุญุฏูุซ ุงูุฌุฏูู ุจูุงุก ุนูู ุงูููุงุชุฑ
  function ุชุญุฏูุซ_ุงูุฌุฏูู() {
    const tbody = document.querySelector("#ุฌุฏูู-ูุตุฑููุงุช tbody");
    tbody.innerHTML = "";

    const ููุชุฑููุน = document.getElementById("ููุชุฑ-ููุน").value;
    const ููุชุฑุชุตููู = document.getElementById("ููุชุฑ-ุชุตููู").value;
    const ููุชุฑุชุงุฑูุฎูู = document.getElementById("ููุชุฑ-ุชุงุฑูุฎ-ูู").value;
    const ููุชุฑุชุงุฑูุฎุฅูู = document.getElementById("ููุชุฑ-ุชุงุฑูุฎ-ุฅูู").value;

    let ุจูุงูุงุช_ูููุชุฑุฉ = ุจูุงูุงุช.filter(ุนูุตุฑ
